services:
  - type: web
    name: nest-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd Backend && npm install --include=dev && npx prisma generate && npm run build
    startCommand: cd Backend && node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DEBUG_OTP
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: QB_CLIENT_ID
        value: "ABzXz08BjZ2oE2u9u4dRQomYmBNM8nEg0yaDKLVTYsSOolehep"
      - key: QB_CLIENT_SECRET
        sync: false
      - key: QB_REDIRECT_URI
        value: "https://nest-backend-mddn.onrender.com/api/quickbooks/callback"
      - key: QB_AUTH_URL
        value: https://appcenter.intuit.com/connect/oauth2
      - key: QB_TOKEN_URL
        value: https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer
      - key: QB_API_BASE_URL
        value: https://sandbox-quickbooks.api.intuit.com/v3/company
      - key: QB_ENVIRONMENT
        value: development
