export const permissionDefaultsMap: Record<string, Record<string, boolean>> = {
  VIEWER: {
    'scan:read': true,
    'scan:write': false,
    'scan:execute': false,
    'map:read': false,
    'map:write': false,
    'map:execute': false,
    'sync:read': false,
    'sync:execute': false,
    'locations:read': false,
    'locations:write': false,
  },
  STAFF: {
    'scan:read': true,
    'scan:write': true,
    'scan:execute': true,
    'map:read': false,
    'map:write': false,
    'map:execute': false,
    'sync:read': true,
    'sync:execute': true,
    'locations:read': false,
    'locations:write': false,
  },
  ACCOUNTANT: {
    'scan:read': true,
    'scan:write': true,
    'scan:execute': true,
    'map:read': true,
    'map:write': true,
    'map:execute': true,
    'sync:read': true,
    'sync:execute': true,
    'locations:read': true,
    'locations:write': true,
  },
  ADMIN: {
    'scan:read': true,
    'scan:write': true,
    'scan:execute': true,
    'map:read': true,
    'map:write': true,
    'map:execute': true,
    'sync:read': true,
    'sync:execute': true,
    'locations:read': true,
    'locations:write': true,
  },
};
